### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by Bejixd** [akbaryahya/YuukiPS-Launcher#1]
Hi I have a problem I still haven’t solved. I need help ╥﹏╥
![IMG_20220903_183530_233](https://user-images.githubusercontent.com/107890992/188277921-1b53e8d6-d711-44d7-929b-e77a33b9e8c3.jpg)

**Comment by akbaryahya** [comment]
You need Net 6 https://dotnet.microsoft.com/download/dotnet

**Comment by Bejixd** [comment]
> You need Net 6 https://dotnet.microsoft.com/download/dotnet

nope. I`ve net 6.0 but error still remains

**Comment by tigr26gg** [comment]
здравствуйте что если у меня вместо genshin.yuuki.me написано login.yuuki.me и на сервере 3.2 вылетает ошибка 4206 а на остальных 4214
![Снимок экрана (2)](https://user-images.githubusercontent.com/126909290/222813020-3e50ad50-3572-41c6-b7a8-0a3ffe65b583.png)
