### ISSUE TITLE
choose game folder error

### ISSUE THREAD

**Issue by GJKen** [akbaryahya/YuukiPS-Launcher#3]
> For details on calling just-in-time (JIT) debugging instead of this dialog,
> See end of this message.
> 
> ************** exception text **************
> Newtonsoft.Json.JsonSerializationException: Error converting value "cn_gf01" to type 'System.Nullable`1[YuukiPS_Launcher.Game.Genshin.Settings+ServerRegionID]'. Path 'selectedServerName', line 1, position 131.
>  ---> System.ArgumentException: Requested value 'cn_gf01' was not found.
>    at Newtonsoft.Json.Utilities.EnumUtils.ParseEnum(Type enumType, NamingStrategy namingStrategy, String value, Boolean disallowNumber)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
>    --- End of inner exception stack trace ---
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
>    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
>    at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
>    at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
>    at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
>    at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
>    at YuukiPS_Launcher.Game.Genshin.Settings.GetVoiceLanguageID() in D:\a\YuukiPS-Launcher\YuukiPS-Launcher\Game\Genshin\Settings.cs:line 91
>    at YuukiPS_Launcher.Main.CheckVersionGame() in D:\a\YuukiPS-Launcher\YuukiPS-Launcher\Main.cs:line 220
>    at YuukiPS_Launcher.Main.Set_LA_Select_Click(Object sender, EventArgs e) in D:\a\YuukiPS-Launcher\YuukiPS-Launcher\Main.cs:line 811
>    at System.Windows.Forms.Control.OnClick(EventArgs e)
>    at System.Windows.Forms.Button.OnClick(EventArgs e)
>    at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
>    at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>    at System.Windows.Forms.Control.WndProc(Message& m)
>    at System.Windows.Forms.ButtonBase.WndProc(Message& m)
>    at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
>    at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
> 
> 
> ************** loaded assembly  **************
> System.Private.CoreLib
>     assembly version:6.0.0.0
>     Win32 version:6.0.522.21309
>     Code base:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Private.CoreLib.dll
> ----------------------------------------
> YuukiPS
>     assembly version:2022.9.28.2255
>     Win32 version:2022.9.28.2255
>     Code base:file:///D:/Program/Genshin%20PW/YuukiPS/YuukiPS.dll
> ----------------------------------------
> System.Runtime
>     assembly version:6.0.0.0
>     Win32 version:6.0.522.21309
>     Code base:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Runtime.dll
> ----------------------------------------
> System.Windows.Forms
>     assembly version:6.0.2.0
>     Win32 version:6.0.422.16407
>     Code base:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.5/System.Windows.Forms.dll
> ----------------------------------------
> System.ComponentModel.Primitives
>     assembly version:6.0.0.0
>     Win32 version:6.0.522.21309
>     Code base:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.ComponentModel.Primitives.dll
> ----------------------------------------
> System.Windows.Forms.Primitives
>     assembly version:6.0.2.0
>     Win32 version:6.0.422.16407
>     Code base:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.5/System.Windows.Forms.Primitives.dll
> ----------------------------------------
> System.Runtime.InteropServices
>     assembly version:6.0.0.0
>     Win32 version:6.0.522.21309
>     Code base:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Runtime.InteropServices.dll
> ----------------------------------------
> System.Drawing.Primitives
>     assembly version:6.0.0.0
>     Win32 version:6.0.522.21309
>     Code base:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Drawing.Primitives.dll
> ----------------------------------------
> System.Collections.Specialized
>     assembly version:6.0.0.0
>     Win32 version:6.0.522.21309
>     Code base:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Collections.Specialized.dll
> ----------------------------------------
> System.Threading
>     assembly version:6.0.0.0
>     Win32 version:6.0.522.21309
>     Code base:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Threading.dll
> ----------------------------------------
> System.Diagnostics.TraceSource
>     assembly version:6.0.0.0
>     Win32 version:6.0.522.21309
>     Code base:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Diagnostics.TraceSource.dll
> ----------------------------------------
> System.Collections
>     assembly version:6.0.0.0
>     Win32 version:6.0.522.21309
>     Code base:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Collections.dll
> ----------------------------------------
> System.Drawing.Common
>     assembly version:6.0.0.0
>     Win32 version:6.0.422.16404
>     Code base:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.5/System.Drawing.Common.dll
> ----------------------------------------
> Microsoft.Win32.Primitives
>     assembly version:6.0.0.0
>     Win32 version:6.0.522.21309
>     Code base:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/Microsoft.Win32.Primitives.dll
> ----------------------------------------
> System.ComponentModel.EventBasedAsync
>     assembly version:6.0.0.0
>     Win32 version:6.0.522.21309
>     Code base:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.ComponentModel.EventBasedAsync.dll
> ----------------------------------------
> System.Threading.Thread
>     assembly version:6.0.0.0
>     Win32 version:6.0.522.21309
>     Code base:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Threading.Thread.dll
> ----------------------------------------
> Accessibility
>     assembly version:4.0.0.0
>     Win32 version:6.0.422.16407
>     Code base:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.5/Accessibility.dll
> ----------------------------------------
> System.ComponentModel.TypeConverter
>     assembly version:6.0.0.0
>     Win32 version:6.0.522.21309
>     Code base:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.ComponentModel.TypeConverter.dll
> ----------------------------------------
> System.Numerics.Vectors
>     assembly version:6.0.0.0
>     Win32 version:6.0.522.21309
>     Code base:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Numerics.Vectors.dll
> ----------------------------------------
> System.ComponentModel
>     assembly version:6.0.0.0
>     Win32 version:6.0.522.21309
>     Code base:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.ComponentModel.dll
> ----------------------------------------
> Microsoft.Win32.SystemEvents
>     assembly version:6.0.0.0
>     Win32 version:6.0.422.16404
>     Code base:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.5/Microsoft.Win32.SystemEvents.dll
> ----------------------------------------
> System.Memory
>     assembly version:6.0.0.0
>     Win32 version:6.0.522.21309
>     Code base:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Memory.dll
> ----------------------------------------
> System.Collections.NonGeneric
>     assembly version:6.0.0.0
>     Win32 version:6.0.522.21309
>     Code base:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Collections.NonGeneric.dll
> ----------------------------------------
> System.Console
>     assembly version:6.0.0.0
>     Win32 version:6.0.522.21309
>     Code base:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Console.dll
> ----------------------------------------
> System.Text.Encoding.Extensions
>     assembly version:6.0.0.0
>     Win32 version:6.0.522.21309
>     Code base:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Text.Encoding.Extensions.dll
> ----------------------------------------
> Newtonsoft.Json
>     assembly version:13.0.0.0
>     Win32 version:13.0.1.25517
>     Code base:file:///D:/Program/Genshin%20PW/YuukiPS/Newtonsoft.Json.dll
> ----------------------------------------
> netstandard
>     assembly version:2.1.0.0
>     Win32 version:6.0.522.21309
>     Code base:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/netstandard.dll
> ----------------------------------------
> System.Runtime.Serialization.Formatters
>     assembly version:6.0.0.0
>     Win32 version:6.0.522.21309
>     Code base:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Runtime.Serialization.Formatters.dll
> ----------------------------------------
> System.Collections.Concurrent
>     assembly version:6.0.0.0
>     Win32 version:6.0.522.21309
>     Code base:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Collections.Concurrent.dll
> ----------------------------------------
> System.Linq.Expressions
>     assembly version:6.0.0.0
>     Win32 version:6.0.522.21309
>     Code base:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Linq.Expressions.dll
> ----------------------------------------
> System.Runtime.Numerics
>     assembly version:6.0.0.0
>     Win32 version:6.0.522.21309
>     Code base:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Runtime.Numerics.dll
> ----------------------------------------
> System.Private.Uri
>     assembly version:6.0.0.0
>     Win32 version:6.0.522.21309
>     Code base:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Private.Uri.dll
> ----------------------------------------
> System.Linq
>     assembly version:6.0.0.0
>     Win32 version:6.0.522.21309
>     Code base:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Linq.dll
> ----------------------------------------
> System.ObjectModel
>     assembly version:6.0.0.0
>     Win32 version:6.0.522.21309
>     Code base:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.ObjectModel.dll
> ----------------------------------------
> System.Runtime.Serialization.Primitives
>     assembly version:6.0.0.0
>     Win32 version:6.0.522.21309
>     Code base:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Runtime.Serialization.Primitives.dll
> ----------------------------------------
> System.Data.Common
>     assembly version:6.0.0.0
>     Win32 version:6.0.522.21309
>     Code base:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Data.Common.dll
> ----------------------------------------
> System.Xml.ReaderWriter
>     assembly version:6.0.0.0
>     Win32 version:6.0.522.21309
>     Code base:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Xml.ReaderWriter.dll
> ----------------------------------------
> System.Private.Xml
>     assembly version:6.0.0.0
>     Win32 version:6.0.522.21309
>     Code base:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Private.Xml.dll
> ----------------------------------------
> System.Reflection.Emit.ILGeneration
>     assembly version:6.0.0.0
>     Win32 version:6.0.522.21309
>     Code base:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Reflection.Emit.ILGeneration.dll
> ----------------------------------------
> System.Reflection.Emit.Lightweight
>     assembly version:6.0.0.0
>     Win32 version:6.0.522.21309
>     Code base:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Reflection.Emit.Lightweight.dll
> ----------------------------------------
> System.Reflection.Primitives
>     assembly version:6.0.0.0
>     Win32 version:6.0.522.21309
>     Code base:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Reflection.Primitives.dll
> ----------------------------------------
> Anonymously Hosted DynamicMethods Assembly
>     assembly version:0.0.0.0
>     Win32 version:6.0.522.21309
>     Code base:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Private.CoreLib.dll
> ----------------------------------------
> Microsoft.Win32.Registry
>     assembly version:6.0.0.0
>     Win32 version:6.0.522.21309
>     Code base:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/Microsoft.Win32.Registry.dll
> ----------------------------------------
> System.Diagnostics.Process
>     assembly version:6.0.0.0
>     Win32 version:6.0.522.21309
>     Code base:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Diagnostics.Process.dll
> ----------------------------------------
> RestSharp
>     assembly version:108.0.2.0
>     Win32 version:108.0.2
>     Code base:file:///D:/Program/Genshin%20PW/YuukiPS/RestSharp.dll
> ----------------------------------------
> System.Net.Http
>     assembly version:6.0.0.0
>     Win32 version:6.0.522.21309
>     Code base:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Net.Http.dll
> ----------------------------------------
> System.Net.Primitives
>     assembly version:6.0.0.0
>     Win32 version:6.0.522.21309
>     Code base:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Net.Primitives.dll
> ----------------------------------------
> System.Text.Json
>     assembly version:6.0.0.0
>     Win32 version:6.0.522.21309
>     Code base:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Text.Json.dll
> ----------------------------------------
> System.Diagnostics.Tracing
>     assembly version:6.0.0.0
>     Win32 version:6.0.522.21309
>     Code base:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Diagnostics.Tracing.dll
> ----------------------------------------
> System.Diagnostics.DiagnosticSource
>     assembly version:6.0.0.0
>     Win32 version:6.0.522.21309
>     Code base:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Diagnostics.DiagnosticSource.dll
> ----------------------------------------
> System.Net.Security
>     assembly version:6.0.0.0
>     Win32 version:6.0.522.21309
>     Code base:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Net.Security.dll
> ----------------------------------------
> System.Security.Cryptography.X509Certificates
>     assembly version:6.0.0.0
>     Win32 version:6.0.522.21309
>     Code base:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Security.Cryptography.X509Certificates.dll
> ----------------------------------------
> System.Security.Cryptography.Primitives
>     assembly version:6.0.0.0
>     Win32 version:6.0.522.21309
>     Code base:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Security.Cryptography.Primitives.dll
> ----------------------------------------
> System.Web.HttpUtility
>     assembly version:6.0.0.0
>     Win32 version:6.0.522.21309
>     Code base:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Web.HttpUtility.dll
> ----------------------------------------
> System.Net.Sockets
>     assembly version:6.0.0.0
>     Win32 version:6.0.522.21309
>     Code base:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Net.Sockets.dll
> ----------------------------------------
> System.Threading.Overlapped
>     assembly version:6.0.0.0
>     Win32 version:6.0.522.21309
>     Code base:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Threading.Overlapped.dll
> ----------------------------------------
> System.Net.NameResolution
>     assembly version:6.0.0.0
>     Win32 version:6.0.522.21309
>     Code base:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Net.NameResolution.dll
> ----------------------------------------
> System.Threading.ThreadPool
>     assembly version:6.0.0.0
>     Win32 version:6.0.522.21309
>     Code base:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Threading.ThreadPool.dll
> ----------------------------------------
> System.Security.Principal.Windows
>     assembly version:6.0.0.0
>     Win32 version:6.0.522.21309
>     Code base:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Security.Principal.Windows.dll
> ----------------------------------------
> System.Security.Claims
>     assembly version:6.0.0.0
>     Win32 version:6.0.522.21309
>     Code base:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Security.Claims.dll
> ----------------------------------------
> System.Security.Cryptography.Encoding
>     assembly version:6.0.0.0
>     Win32 version:6.0.522.21309
>     Code base:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Security.Cryptography.Encoding.dll
> ----------------------------------------
> System.IO.Compression
>     assembly version:6.0.0.0
>     Win32 version:6.0.522.21309
>     Code base:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.IO.Compression.dll
> ----------------------------------------
> DiscordRPC
>     assembly version:1.0.175.0
>     Win32 version:1.0.175.0
>     Code base:file:///D:/Program/Genshin%20PW/YuukiPS/DiscordRPC.dll
> ----------------------------------------
> System.IO.Pipes
>     assembly version:6.0.0.0
>     Win32 version:6.0.522.21309
>     Code base:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.IO.Pipes.dll
> ----------------------------------------
> System.Net.Ping
>     assembly version:6.0.0.0
>     Win32 version:6.0.522.21309
>     Code base:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Net.Ping.dll
> ----------------------------------------
> System.Runtime.CompilerServices.Unsafe
>     assembly version:6.0.0.0
>     Win32 version:6.0.522.21309
>     Code base:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Runtime.CompilerServices.Unsafe.dll
> ----------------------------------------
> System.Runtime.Loader
>     assembly version:6.0.0.0
>     Win32 version:6.0.522.21309
>     Code base:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Runtime.Loader.dll
> ----------------------------------------
> System.Windows.Forms.resources
>     assembly version:6.0.2.0
>     Win32 version:6.0.422.16407
>     Code base:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.5/zh-Hans/System.Windows.Forms.resources.dll
> ----------------------------------------
> System.Diagnostics.StackTrace
>     assembly version:6.0.0.0
>     Win32 version:6.0.522.21309
>     Code base:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Diagnostics.StackTrace.dll
> ----------------------------------------
> System.Reflection.Metadata
>     assembly version:6.0.0.0
>     Win32 version:6.0.522.21309
>     Code base:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Reflection.Metadata.dll
> ----------------------------------------
> System.Collections.Immutable
>     assembly version:6.0.0.0
>     Win32 version:6.0.522.21309
>     Code base:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Collections.Immutable.dll
> ----------------------------------------
> 
> ************** JIT debugging **************

**Comment by akbaryahya** [comment]
Are you using chinese version? there seems to be something missing "cn_gf01" so that it raises this error

**Comment by GJKen** [comment]
> Are you using chinese version? there seems to be something missing "cn_gf01" so that it raises this error

yes, what is 'cn_gf01', i don't know how to solve it

**Comment by burninghair** [comment]
I also met this problem,when i choose "choose" to open folder,then the program turnoff itself, how to solve it?
